"""add is_active column to todo

Revision ID: 9f45a9a9d061
Revises: befbe2eb0653
Create Date: 2021-04-04 19:00:11.792615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f45a9a9d061'
down_revision = 'befbe2eb0653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('to_do', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('to_do', 'is_active')
    # ### end Alembic commands ###
